server:
  app:
    auto: true
  servlet:
    context-path: /ms-test/v1

spring:
  profiles:
    active: ${PROFILE:local}
  application:
    name: ms-test

#Spring boot actuator config for health check
endpoints:
  health:
    sensitive: false
    mapping:
      DOWN: SERVICE_UNAVAILABLE

gateway:
  mock-server: "https://jsonplaceholder.typicode.com"
  soap-server: "http://webservices.oorsprong.org/websamples.countryinfo"